siteTitle = 'Điểm Hẹn Đà Lạt '
siteDescr = 'Địa điểm du lịch + Ăn uống Đà Lạt'
siteDescription = "Du lịch Đà Lạt "
siteUrl = "http://diemhendalat.com"
siteBandcampUrl = 'http://diemhendalat.com'
siteMenuOne = 'Du Lịch Đà Lạt'
siteMenuTwo = 'Khách Sạn'
siteMenuThree = 'Cẩm Nang'

siteSoundcloudUrl = 'https://soundcloud.com/sentimony'
siteFacebookUrl = 'https://www.facebook.com/OdayakaPhuQuoc'
siteDiscogsUrl = 'https://www.discogs.com/label/82598-Sentimony-Records'
siteTwitterUrl = 'https://twitter.com/OdayakaPhuQuoc'
siteGoogleplusUrl = ''
siteGithubUrl = 'https://github.com'
siteYoutubeUrl = 'https://www.youtube.com/channel/UC2xhVmkOYPKibhJm3f0f3hw'

linkPrefix = '/'
